import type { HmrcQuestionnaireResponse } from "./types";

export interface HmrcQuestionnaireQuestion {
  id: string;
  title: string;
  prompt: string;
  yesNo?: boolean;
  defaultAnswer?: string;
}

export const HMRC_QUESTIONS: HmrcQuestionnaireQuestion[] = [
  {
    id: "q1",
    title: "1. Activity start",
    prompt: "When did you begin your cryptoasset activities?",
  },
  {
    id: "q2",
    title: "2. CGT calculation",
    prompt:
      "Provide full capital gains calculations with Section 104 matching and pooling, opening and closing pools, and transactions within the pools.",
    defaultAnswer:
      "Generated by TinoTax after finalizing the tax year: disposals_calculation.csv, s104_pool_movements.csv, and s104_pool_opening_closing.csv.",
  },
  {
    id: "q3",
    title: "3. S104 not applied",
    prompt: "If Section 104 matching and pooling rules have not been applied, explain why.",
    defaultAnswer:
      "Section 104 pooling is applied by TinoTax, after same-day and 30-day matching rules.",
  },
  {
    id: "q4",
    title: "4. Calculator used",
    prompt:
      "Confirm which commercial cryptoasset tax calculator was used and provide calculation data, outputs, and summaries.",
    defaultAnswer:
      "TinoTax was used. Calculation data, outputs, summaries, review decisions, and audit files are held in the project tax and evidence pack folders.",
  },
  {
    id: "q5",
    title: "5. Platforms and protocols",
    prompt:
      "State which trading platforms, exchanges, wallets, and protocols were used, including centralised exchanges, decentralised exchanges, and decentralised protocols.",
  },
  {
    id: "q6",
    title: "6. Unedited data files",
    prompt:
      "Provide full and unedited trading data files for each platform, exchange, protocol, and wallet used in the tax year.",
    defaultAnswer:
      "TinoTax stores unedited CEX CSV originals under raw/cex and wallet API pages under raw/<chain>/<wallet>. The evidence pack raw_data_index.csv lists each raw file and hash.",
  },
  {
    id: "q7",
    title: "7. Forks",
    prompt: "Do you have any cryptoassets which have forked? If so, provide further details.",
    yesNo: true,
  },
  {
    id: "q8",
    title: "8. Airdrops",
    prompt:
      "Have you received and subsequently sold any coins or tokens from airdrops? Provide coin/token, amount, receipt date, and disposal details.",
    yesNo: true,
  },
  {
    id: "q9",
    title: "9. Compensation",
    prompt:
      "Have you received compensation for the loss of any cryptoassets? Provide details of the compensation received.",
    yesNo: true,
  },
  {
    id: "q10",
    title: "10. Employment",
    prompt:
      "Have any cryptoassets been provided by employment or self-employment? Include asset, quantity, receipt date, valuation, and whether PAYE was operated.",
    yesNo: true,
  },
  {
    id: "q11",
    title: "11. Mining or staking",
    prompt:
      "Have you mined or staked? Explain how receipts were accounted for, whether later disposed of, and whether disposals are in the CGT calculations.",
    yesNo: true,
  },
  {
    id: "q12",
    title: "12. Goods or services",
    prompt:
      "Have you used cryptoassets to acquire goods, services, or other property? Provide further information.",
    yesNo: true,
  },
  {
    id: "q13",
    title: "13. Source of funds",
    prompt: "Explain where the funds used to fund your cryptoasset activities originated.",
  },
];

export function initialHmrcResponses(): HmrcQuestionnaireResponse[] {
  return HMRC_QUESTIONS.map((question) => ({
    id: question.id,
    question: question.prompt,
    answer: question.defaultAnswer ?? "",
    choice: question.yesNo ? "unknown" : "",
  }));
}
