//! Small helpers for the generated markdown files.

use anyhow::{Context, Result};
use camino::Utf8Path;

pub fn write_md(dir: &Utf8Path, name: &str, text: &str) -> Result<()> {
    let path = dir.join(name);
    std::fs::write(&path, text).with_context(|| format!("writing {path}"))?;
    Ok(())
}

/// `calculator_statement.md` — HMRC question 4 asks which commercial
/// calculator was used; this states the tool, version and pipeline.
pub fn calculator_statement(tax_year: &str) -> String {
    format!(
        "# Calculator statement\n\n\
         Calculations for tax year {tax_year} were produced with **TinoTax v{version}**\n\
         (https://github.com/trilltino/tinotax), an auditable open-source pipeline:\n\n\
         1. `fetch` / `import-cex` — raw wallet pages and unedited exchange CSVs are\n\
            stored immutably and hashed (BLAKE3)\n\
         2. `normalise` — raw data becomes source-traceable events\n\
         3. `review export-all` / `review apply` — every human decision is recorded\n\
            as an override; raw and normalised data are never edited\n\
         4. `ledger build` / `ledger price` — reviewed ledger, valued in GBP with a\n\
            per-value pricing audit\n\
         5. `calculate uk` — same-day, 30-day and Section 104 matching per HMRC's\n\
            Cryptoassets Manual\n\
         6. `pack hmrc` — this evidence pack\n\n\
         Every output row carries identifiers tracing it back to the raw evidence\n\
         file it came from (see `raw_data_index.csv` and `audit_manifest.json` in\n\
         the project's `out/` folder).\n",
        version = env!("CARGO_PKG_VERSION"),
    )
}

/// The pack's own table of contents.
pub fn pack_readme(tax_year: &str, questionnaire_pending: bool) -> String {
    let mut text = format!(
        "# TinoTax evidence pack — {tax_year}\n\n\
         Prepared to support a Self Assessment return and HMRC's standard\n\
         cryptoasset information requests. Generated by TinoTax v{version}.\n\n\
         | File | What it answers |\n\
         |---|---|\n\
         | `hmrc_questions_draft.md` | Draft responses to HMRC's 13 standard questions |\n\
         | `self_assessment_crypto_summary.csv` | Headline figures for the return |\n\
         | `disposals_calculation.csv` | Every disposal with full matching breakdown |\n\
         | `s104_pool_movements.csv` | Every Section 104 pool change |\n\
         | `s104_pool_opening_closing.csv` | Pool balances at the year boundaries |\n\
         | `income_summary.csv` | Staking/mining/airdrop/other receipts |\n\
         | `platforms_protocols_used.csv` | Exchanges, chains and platforms used |\n\
         | `counterparties.csv` | Every contract/protocol the wallets touched (HMRC Q5) |\n\
         | `wallet_addresses.csv` | Declared wallet addresses |\n\
         | `raw_data_index.csv` | Every raw evidence file with its BLAKE3 hash |\n\
         | `pricing_audit.csv` | Where every GBP valuation came from |\n\
         | `manual_review_decisions.csv` | The human decisions applied to the data |\n\
         | `change_log.csv` | Full history of every review edit |\n\
         | `unresolved_review_items.csv` | Anything still open — read this first |\n\
         | `calculator_statement.md` | The tool and method used |\n\
         | `source_of_funds_notes.md` | Source of funds (from the questionnaire) |\n\
         | `assumptions_and_limitations.md` | Method, assumptions, known limits |\n",
        version = env!("CARGO_PKG_VERSION"),
    );
    if questionnaire_pending {
        text.push_str(
            "\n> **Action needed:** `questionnaire.toml` in the project root has\n\
             > unanswered questions (source of funds, employment, forks,\n\
             > compensation, goods/services). Fill it in and re-run `pack hmrc`.\n",
        );
    }
    text
}
